//
//  ContentView.swift
//  FrontSdkExampleSwiftUI
//
//  Created by Ruturaj Choudhari on 1/28/25.
//

import SwiftUI
import FrontSdk
import WebKit
import CryptoKit

struct ContentView: View {
    @State private var showingSheet = false
    @StateObject private var viewModel = FrontChatViewModel()

    // Set to the value of your chat id obtained from the code snippet shown here:
    // https://help.front.com/en/articles/2049#install_front_chat_on_your_website
    @State private var chatId = ""
    
    var body: some View {
        
        HStack {
            // A simple button to launch FrontChatView
            Button("Open Chat") {
                showingSheet.toggle()
            }
            .disabled(chatId.isEmpty)
            .sheet(isPresented: $showingSheet) {
                NavigationStack {
                    // Example of how to handle failed loading
                    if viewModel.loadingStatus == .failedLoading {
                        failedToLoadView()
                    } else {
                        frontChatView()
                    }
                }
                // Example of how to handle an exception from the webview that FrontChatView uses
                .alert("Error", isPresented: $viewModel.didEncounterUnrecoverableError) {
                    Button("Close Chat") {
                        viewModel.reset()
                        showingSheet.toggle()
                    }
                    Button("Start New Chat") {
                        viewModel.reset()
                        viewModel.restart()
                    }
                } message: {
                    Text(viewModel.unrecoverableErrorMessage ?? "")
                }
            }
        }
    }
    
    func frontChatView() -> some View {
        let config = FrontChatConfig(
            chatId: chatId
            // To test with verified users, uncomment below and set values as described here:
            // https://dev.frontapp.com/docs/identify-users
            /*
            ,email: "john.doe@acme.com",
            userHash: "<user hash generated by your backend>"),
            name: "John Doe",
            customFields: ["custom_field_1": .string("value_1")],
            contact: Contact(
               email: john.doe@acme.com,
               customFields: ["custom_field_1": .string("value_1")]
            )
            */
        )
        return ZStack {
            FrontChatView(config: config, viewModel: viewModel, enableLoadingIndicator: false)
                .navigationBarTitle("Welcome", displayMode: .inline)
                .toolbar {
                    ToolbarItem(placement: .topBarLeading) {
                        Button(action: {
                            // Example of how to switch to the user's conversation history
                            viewModel.navigate(to: .conversationHistory)
                        }) {
                            Label("", systemImage: "chevron.left")
                        }
                    }
                    ToolbarItem(placement: .topBarTrailing) {
                        Button(action: {
                            // Example of how to end the current conversation and start a new one for the user
                            viewModel.restart()
                        }) {
                            Label("", systemImage: "arrow.triangle.2.circlepath")
                        }
                    }
                    ToolbarItem(placement: .topBarTrailing) {
                        Button(action: {
                            showingSheet = false
                        }) {
                            Label("", systemImage: "chevron.down")
                        }
                    }
                }

            // This shows how to handle the FrontChatView loading state. It replicates the default behavior of the SDK here but you can adjust to your needs.
            if viewModel.loadingStatus == .startedLoading {
                ProgressView()
                    .progressViewStyle(CircularProgressViewStyle())
                    .scaleEffect(1.5)
            }
        }
    }
    
    func failedToLoadView() -> some View {
        VStack {
            Text("Failed to load Chat.")
            Button("Ok") {
                viewModel.reset()
                showingSheet = false
            }
        }
    }
}

#Preview {
    ContentView()
}
